# -*- coding: utf-8 -*-
"""Language Translator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1fTknrHkx6JMEapF3R0njfa7URiGWVU
"""

# Install the package (if not already installed)
!pip install googletrans==4.0.0rc1

# Import the required modules
import googletrans
from googletrans import Translator

# Initialize the translator
translator = Translator()

# Print available languages (optional)
print("Supported languages:")
for code, lang in googletrans.LANGUAGES.items():
    print(f"{code}: {lang}")

# Example translation
text = input("Enter text to translate: ")
dest_lang = input("Enter target language code (e.g., 'fr' for French, 'es' for Spanish): ")
# Translate the text
translation = translator.translate(text, dest=dest_lang)
# Display results
print(f"\nOriginal Text: {text}")
print(f"Translated Text ({dest_lang}): {translation.text}")